### ISSUE TITLE
EcoCampus: Create weather file for years 2004 - till date from NUS data

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#513] opened 2017-02-27 07:59 UTC
Create epw weather file from open source NUS data.

https://inetapps.nus.edu.sg/fas/geog/ajxdirList.aspx

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-02-28 02:16
All the files downloaded from the website, when opened lead to the following error:

"The file you are trying to open, 'filename.xls' is in a different format than specified by the file extension. Verify that the file is not corrupted and is from a trusted source before opening the file. Do you want to open the file now?"

For now, I figured out two ways to deal with this error

1. Open the file -> Get the error and press 'OK' -> Save the file into 'Excel Workbook' format manually using 'Save As' option

2. This involves modifying the registry with the following procedure:

If you don’t want to look for a solution, but just want to solve the problem, insert this key in your registry to suppress the notification:

[HKEY_CURRENT_USER\Software\Microsoft\Office\12.0\Excel\Security] “ExtensionHardening”=dword:00000000

You can accomplish the above by doing the following:

Open your Registry (Start -> Run -> regedit.exe)
Navigate to HKEY_CURRENT_USER\SOFTWARE\MICROSOFT\OFFICE\12.0\EXCEL\SECURITY
Right click in the right window and choose New -> DWORD
Type “ExtensionHardening” as the name (without the quotes)
Verify that the data has the value “0″

http://stackoverflow.com/questions/940045/how-to-suppress-the-file-corrupt-warning-at-excel-download

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-02-28 02:18
The conversion into either 'xls' or 'xlsx' format is essential as there are a large number of files and appending them manually doesn't make sense. Hence Python is used to append these files, which will accept the above mentioned formats

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-02-28 06:11
@JIMENOFONSECA : I am going through the .epw files. I observed that the columns do not have any names associated with them in the file. Is there a legend, which says what each individual column is about?

**Comment by gabriel-happle** [comment] 2017-02-28 06:40
http://bigladdersoftware.com/epx/docs/8-2/auxiliary-programs/epw-csv-format-inout.html#epw-csv-format-inout

**Comment by gabriel-happle** [comment] 2017-02-28 06:42
@BhargavaKrishnaSreepathi maybe you can also use this
https://www.advancedrenamer.com/
it's cool. I have used it before

**Comment by JIMENOFONSECA** [comment] 2017-02-28 06:49
Yes!, check in cea/ utilities/epw reader. Py

That is the name of the columns..

Best, Jimeno

On 28 Feb 2017, at 14:42, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@BhargavaKrishnaSreepathi<https://github.com/BhargavaKrishnaSreepathi> maybe you can also use this
https://www.advancedrenamer.com/
it's cool. I have used it before

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-02-28 07:26
For the year 2012: there is data missing from 28/06/2012 to 19/07/2012

**Comment by JIMENOFONSECA** [comment] 2017-02-28 10:21
2003? Do we need data of all those years? Is not only necessary for the time of the measurements?

Older data we can get with interpolation from meteonorm..

Best, Jimeno

On 28 Feb 2017, at 15:26, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


For the year 2012: there is data missing from 28/06/2012 to 19/07/2012

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-01 02:12
After discussing with @JIMENOFONSECA, the weather files are to be generated for the year which has the details about the measured energy consumption. As per @gabriel-happle, we have the hourly chiller loads for some parts in 2014, 2016. So effectively we will be requiring the weather data files for 214 and 2016. Do correct me if I missed something

**Comment by gabriel-happle** [comment] 2017-03-01 04:12
@JIMENOFONSECA which data from the weather file is actually used in the CEA calculation? Could you please make a list?

**Comment by JIMENOFONSECA** [comment] 2017-03-01 07:55
Go to cea/utilities/epw-reader.py
The values passed are used in the cea tool

In radiation main.py
In demand main.py

Best, Jimeno

On 1 Mar 2017, at 12:12, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> which data from the weather file is actually used in the CEA calculation? Could you please make a list?

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-01 08:30
The values passed to the files are as follows:
Radiation.py: 'dayofyear', 'exthorad_Whm2', 'glohorrad_Whm2', 'difhorrad_Whm2'
demand_main.py: 'drybulb_C', 'relhum_percent', 'windspd_ms', 'skytemp_C'

In terms of parameters related to this directly or indirectly are the following:

1. dayofyear (direct from .epw file)
2. exthorad_Whm2 (direct from .epw file)
3. glohorrad_Whm2 (direct from .epw file)
4. difhorrad_Whm2 (direct from .epw file)
5. drybulb_C (direct from .epw file)
6. relhum_percent (direct from .epw file)
7. windspd_ms (direct from .epw file)
8. skytemp_C (calculated using 'drybulb_C', 'dewpoint_C', 'skycover'). This leads to the following parameters

9. dewpoint_C (direct from .epw file)
10. skycover (depends on 'difhorrad_Whm2' and 'glohorrad_Whm2' already determined from .epw file).

The parameters that are available to us from the NUS data are:
a. Date, Time (Useful for parameter 1)
b. Pressure (not useful for above parameters)
c. Air Temp **(?? shall we consider this as wet bulb temp??)**
d. Relative Humidity (useful for Parameter 6)
e. Windspeed (Parameter 7)
f. Wind Direction **(Should we use this??)**
g. Incoming Radiation **(Now how to relate this to other radiations, like parameter 3, 4)**
h. Rainfall **(may be use this for skycover??)**

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-03 02:09
Air temperature is generally the dry bulb temperature 
http://www.engineeringtoolbox.com/dry-wet-bulb-dew-point-air-d_682.html

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-08 02:07
The ratio of 'glohorrad_Whm2' to 'difhorrad_Whm2' varies widely between 1 to 9 (observed in the singapore.epw weather file). The average value for all these cases is '1.795'. If we do not get any other value, we can use this.

There is an alternate way, where we take the average corresponding to each hour of the day and then apply  it to our case. i.e. average of hour 1 of all 365 days and then use it for 2016. I will be working on this till we hear back from SERIS @gabriel-happle: do let me know if you get any information from SERIS

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-08 03:27
@JIMENOFONSECA : a minor technical glitch. 2016 being a leap year, has one extra day so wherever we had 8760 hours need to be changed to 8784 hours. Shall I do this or for simplicity remove 29th February to maintain 8760 hours while running the 'demand_main' file

**Comment by JIMENOFONSECA** [comment] 2017-03-08 03:34
This is a good point.
I will keep it 8760 so we can compare to other years.

best,  Jimeno


On 8 Mar 2017, at 11:27 am, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> : a minor technical glitch. 2016 being a leap year, has one extra day so wherever we had 8760 hours need to be changed to 8784 hours. Shall I do this or for simplicity remove 29th February to maintain 8760 hours while running the 'demand_main' file

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-03-08 03:36
Noted. Thanks

**Comment by gabriel-happle** [comment] 2017-04-25 07:40
Hey @BhargavaKrishnaSreepathi
could you also produce the 2015 weather file.
That is the year we have the most complete electricity data.

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-04-26 06:35
PR#621 takes care of this issue, as the PR is merged, the issue is being closed

**Closed by BhargavaKrishnaSreepathi** 2017-04-26 06:35 UTC
