### ISSUE TITLE
Switch between infiltration models

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#645] opened 2017-05-16 06:35 UTC
The Demand script should offer the possibility to switch bettween ventilation models. 
for this. the interface to Arcgis should provide a list or a tick box indicating which infiltration model to use:

Model A. Simple steady-state
Model B. Dynamic

This will avoid commenting, commenting lines of code once one or the other models is going to be used. I would like to have this functionality to run some sensitivity analysis..

@daren-thomas @gabriel-happle I hope it is ok if I assign this issue to you. do you think it can be done for this sprint? if not please feel free to asign it to Singapore milestone

**Comment by daren-thomas** [comment] 2017-05-16 08:08
See also #641 for a related issue

**Comment by gabriel-happle** [comment] 2017-05-17 08:59
duplicate of #465

**Comment by gabriel-happle** [comment] 2017-06-01 03:39
@daren-thomas let's talk about this and #251 on Friday 02/06? Can you do from 9:00-10:00?

**Comment by daren-thomas** [comment] 2017-06-13 13:24
working on this in the branch `645-switch-between-infiltration-models`

**Comment by daren-thomas** [comment] 2017-06-13 14:22
implemented in PR #674

**Comment by gabriel-happle** [comment] 2017-06-16 01:29
closing this issue!
Yeah! Milestone achieved in time!
Thanks @daren-thomas

**Closed by gabriel-happle** 2017-06-16 01:29 UTC
Labels: duplicate, Priority 1
