### ISSUE TITLE
Create a model for floor heating

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#55] opened 2016-03-11 10:38 UTC
to replace `calc_TABS` which currently uses the same code as `calc_RAD`.

**Comment by shanshanhsieh** [comment] 2016-03-16 07:58
are you referring to calc_TABSH instead? i believe that is the calculation for floor heating from my version.

**Comment by shanshanhsieh** [comment] 2016-03-17 09:21
For PhD in Zurich : )

**Comment by shanshanhsieh** [comment] 2016-05-12 10:16
hey @martin-mosteiro, the "PhD in Zurich" finally arrives!
I spent sometime researching on the models, maybe it will be helpful for you. Let's arrange a time to discuss about it, and then we could hand this issue over to you.

**Comment by shanshanhsieh** [comment] 2016-05-16 09:35
After looking into the models for thermo-active building elements with @martin-mosteiro, the issue is now transferred to him.
However, since Martin will have other tasks for M1, it might be more feasible to set the deadline to M2. What do you think, @JIMENOFONSECA ?

**Closed** 2016-08-19 12:24 UTC
Labels: Priority 2
