### ISSUE TITLE
SIA 2044 thermal loads to CEA incl. TABS and Corrections to standard

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#427] opened 2016-12-01 09:37 UTC
SIA 2044 methods to CEA incl. TABS and corrections to standard from Korrigenda C1 and Korrigenda C2

**Comment by gabriel-happle** [comment] 2016-12-16 07:45
@JIMENOFONSECA, @martin-mosteiro, @daren-thomas 
According to my understanding we are using the TABS calculation in a wrong way.
Please check 3.1.8 in SIA 2044. Floor heating (currently implemented in CEA) should be calculated with the "normal" RC model but separated convection and radiation component of the heating power.
TABS are calculated according to 2.2.7.3 ff with an extended RC model.
I want to fix that, so we have a correct TABS calculation and we can include more variety of heating/cooling systems (floor heating). But the merge moves further and further away. Chances are low I can finish by the end of the year. Maybe we can move everything to next year and couple with OO? What do you think?

**Comment by martin-mosteiro** [comment] 2016-12-16 09:36
As I mentioned during our call, the current version of the calculation does indeed follow 3.1.8 already. However, this uses a hard-coded value of 0.5 for the TABS case. This could be made much simpler/clearer by adding the corresponding variable _f_HC_ mentioned in the standard and set its value depending on whether it's a radiator or a TABS system.

The problem is rather in the temperature controls, which use the wrong temperature (t_s is misused as the surface temperature of the TABS system in the control). The problem is that the way the code is currently structured, the surface temperature calculation is only carried out _after_ the demand calculation, meaning the control would only be established then - that's the reason we discussed 2.2.7.3 on Skype. The way I understood our conversation at that time, this was the main issue that needed to be solved, and it would go along with your substantial restructuring of the code.

Regarding meeting the milestone, as I mentioned back then, I could easily do the fixes we discussed by the milestone if you need help. However, I don't know if it's contradictory to the way you are moving, so it's kind of up to you, I guess.

Also, what is OO?

**Comment by martin-mosteiro** [comment] 2016-12-16 10:06
Okay, after talking to @gabriel-happle and rereading the above message I get the issue. The current CEA doesn't make a distinction between TABS and floor heating and uses the floor heating calculation method from SIA 2044 3.1.8 with the temperature controls for TABS from the EMPA book. This should be fixed and floor heating and TABS be defined individually.

**Closed** 2017-02-09 09:41 UTC
Labels: bug, enhancement, Priority 1
