### ISSUE TITLE
NUS EcoCampus: Standardise Archetype and Building Systems Database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#522] opened 2017-03-01 12:10 UTC
Right now thermal properties and material properties of buildings are partly stored in the archetypes database and partly in the systems database, although they are related. E.g. U-Value of windows (in archetypes) and g-Value of windows (in systems).
Same with facade U-Values and absorptivity / emmissivity.

At the same time, envelope system properties are not part of any shapefile generated. This means, while U-values of windows can be changed easily in ArcGIS, there is no possibility to change the corresponding g-value.

**Comment by JIMENOFONSECA** [comment] 2017-03-02 00:46
Great idea about this. Let's discuss next week how to integrate these things

Best, Jimeno

On 1 Mar 2017, at 20:11, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now thermal properties and material properties of buildings are partly stored in the archetypes database and partly in the systems database, although they are related. E.g. U-Value of windows (in archetypes) and g-Value of windows (in systems).
Same with facade U-Values and absorptivity / emmissivity.

At the same time, envelope system properties are not part of any shapefile generated. This means, while U-values of windows can be changed easily in ArcGIS, there is no possibility to change the corresponding g-value.

**Comment by JIMENOFONSECA** [comment] 2017-03-06 02:31
@gabriel-happle when do you have time and we meet to brainstorm and make a plan about this?

**Comment by JIMENOFONSECA** [comment] 2017-03-21 07:04
DUPLICATE OF #531 I am on it

**Closed** 2017-04-12 04:33 UTC
