### ISSUE TITLE
Buildings age values

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#203] opened 2016-05-18 14:40 UTC
Why are all the data of retrofitting set to 1969? Except for the non-retrofitted buildings.

**Comment by martin-mosteiro** [comment] 2016-05-18 14:50
Just discussed this with Anja :)

Retrofit data should be available online in the cantonal GIS atlas, but we couldn't find it. Furthermore, it appears the building data we got from the city of Zurich is missing retrofit information (the "Mutationsdatum Gebäude", which we could _interpret_ as the renovation year is set to 99999999 for pretty much all buildings). You can find the data in the server under: **//schlueter-server.ethz.ch/schlueter/Teaching/AS/MIBS_BuildingServices/Integrated Design Studios/2015 HS Hochschulquartier/01 Input A/S Preparation/Datenallokation Energie/Daten Stadt Zürich**

We agreed that I should (i) check the GIS atlas again, and/or (b) call our contact person Josef Troxler to ask for further clarification on this issue.

**Comment by amraladdin** [comment] 2016-05-23 08:55
So @martin-mosteiro we should prepare a case where we change some of these values and check the results, how does that sound?

**Comment by martin-mosteiro** [comment] 2016-05-23 09:42
Sounds good. Maybe we can even come up with some assumption about when buildings could've been renovated to present a more fancy-looking case study for the workshop. 



________________________________________
Von: Amr Elesawy [notifications@github.com]
Gesendet: Montag, 23. Mai 2016 10:55
An: architecture-building-systems/CEAforArcGIS
Cc: Mosteiro Romero  Martin; Mention
Betreff: Re: [architecture-building-systems/CEAforArcGIS] Buildings age values (#203)

So @martin-mosteiro<https://github.com/martin-mosteiro> we should prepare a case where we change some of these values and check the results, how does that sound?

�

**Comment by amraladdin** [comment] 2016-05-23 11:15
That's exactly what I had in mind. Let's talk about this Wednesday morning (tomorrow I have a teaching course to attend)?

**Comment by JIMENOFONSECA** [comment] 2016-07-05 02:37
@amraladdin  is this still the case? would you take care of it?

**Comment by amraladdin** [comment] 2016-07-05 12:42
@JIMENOFONSECA yes, we've already discussed this with Arno and we'll try to get information on these buildings (maybe assign an assistant or an intern).

**Comment by amraladdin** [comment] 2016-07-14 10:51
@martin-mosteiro when you're back from vacations, let's take a look at the website again. If we cannot get the information we seek, we should think of hiring a student.

**Comment by martin-mosteiro** [comment] 2016-07-14 13:35
Sure. Let's talk about it on Tuesday?

**Comment by amraladdin** [comment] 2016-08-22 07:58
@martin-mosteiro @JIMENOFONSECA Since we will use the MIBS course to estimate the buildings components retrofit, I suggest we close this issue. Would you agree?

**Comment by martin-mosteiro** [comment] 2016-08-22 08:01
Agreed. We're having a meeting with the City of Zurich later this week in which we will specifically ask for more information on this, but I think in terms of this milestone, the issue is closed.

**Comment by JIMENOFONSECA** [comment] 2016-08-22 08:04
rather than close it, please assign a new milestone to it. @martin-mosteiro  you might want to decide on this based on the Synergy project timeline...

**Comment by martin-mosteiro** [comment] 2016-08-22 08:10
@JIMENOFONSECA Good idea. I just did that.

**Comment by martin-mosteiro** [comment] 2016-10-17 15:11
The MIBS students' data has been incorporated. However, its validity is questionable, since (a) they are not experts, and (b) even an expert would only be able to give a guess on the current stock's renovation dates.

I few a couple solutions:
1. keep the MIBS student data: at least the window renovation rates are generally correct and even a bad guess is better than no guess (as is currently the case with the 1969 renovation date for all components)
2. do a more exhaustive site visit with an expert: time intensive, probably not worth it?
3. develop a statistical calibration model (see issue #369)
4. some combination of the above (e.g. keep MIBS data for now and improve it through calibration)

Opinion? @amraladdin, @JIMENOFONSECA

**Comment by amraladdin** [comment] 2016-10-18 08:29
I believe it depends on what we are aiming for. If it's for the MIBS students, we can go on with their assumptions, it is already a good exercise for them.
However, if we are talking about the approach that would generate more accurate and reliable results, I suggest the following:
- Develope the statistical model.
- Generate results.
- Compare with MIBS assumptions.
- Compare both with real consumption (the data of UZH that the city should provide).
- Draw conclusions and publish in a paper :)

What do you think?

**Comment by amraladdin** [comment] 2017-03-20 16:53
Any ideas on my latest comment in this thread?
@martin-mosteiro according to Jimano's last message on the CEA _group meeting Channel on Slack... Would you categorize this issue as Priority 2 or 3?

**Comment by martin-mosteiro** [comment] 2017-03-20 17:12
Well, I guess that depends. The basic question is: is the online reference case repository meant to contain basic case studies for first time users or is it a repository of our group's case studies?

I have further developed the Hochschulquartier case study on my own computer but have never updated the online reference case because I assumed this was relevant only to Spacergy. However, if the plan is to have an updated repository of all our case studies on Github, I would obviously update the files on Github. @JIMENOFONSECA @daren-thomas opinion?

@amraladdin: why is this relevant? Well, if the reference case repository is meant for first time users, then the case study is okay as-is and we can close the issue. If not, I'd call this Priority 1, at least as far as Spacergy is concerned. The latest version of the case study is based on our students' assumptions and will then be calibrated using the Bayesian method Jimeno presented. As a first step, we're currently working on a sensitivity analysis of the area for CISBAT.

**Comment by JIMENOFONSECA** [comment] 2017-03-21 01:15
So the reference case is a private repository and should have the cases the group is working on, including hochschule quartier. Be aware that there are issues that will change the strucutre of the case studies. So we use the repository to do this. We should store measured data in there too so be careful to not run the data helper on those cases.

The examples folder in the public repository will have just one case for testing and first time users

Best, Jimeno

On 21 Mar 2017, at 01:12, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, I guess that depends. The basic question is: is the online reference case repository meant to contain basic case studies for first time users or is it a repository of our group's case studies?

I have further developed the Hochschulquartier case study on my own computer but have never updated the online reference case because I assumed this was relevant only to Spacergy. However, if the plan is to have an updated repository of all our case studies on Github, I would obviously update the files on Github. @JIMENOFONSECA<https://github.com/JIMENOFONSECA> @daren-thomas<https://github.com/daren-thomas> opinion?

@amraladdin<https://github.com/amraladdin>: why is this relevant? Well, if the reference case repository is meant for first time users, then the case study is okay as-is and we can close the issue. If not, I'd call this Priority 1, at least as far as Spacergy is concerned. The latest version of the case study is based on our students' assumptions and will then be calibrated using the Bayesian method Jimeno presented. As a first step, we're currently working on a sensitivity analysis of the area for CISBAT.

**Comment by martin-mosteiro** [comment] 2017-03-21 09:21
Okay then – I will update all files for the HSQ case study accordingly.

Back to @amraladdin's question, then, the issue described is no longer true. So I'd be okay with closing it, even.

**Comment by amraladdin** [comment] 2017-03-21 09:32
I agree... @JIMENOFONSECA do you also agree to close this issue?

**Comment by JIMENOFONSECA** [comment] 2017-03-21 11:57
sure, i will close it then

**Closed by JIMENOFONSECA** 2017-03-21 11:57 UTC
Labels: Priority 3
